### ISSUE TITLE
One character per SteamID but with possibilty to login using any local character

### ISSUE THREAD

**Issue by Juraszka** [blaxxun-boop/ServerCharacters#24]
ServerCharacter now have option to allow only one character per SteamID and player can't login with another character.
Can I suggest to make option like "World of Valheim SSC" (https://valheim.thunderstore.io/package/HackShardGaming/World_of_Valheim_SSC/) where player can login to server with any local character which name and look is aplied to current session but stats, inventory and anything else is server side based on SteamID?

Notification could notify something like "SteamID login to server as CharacterName"

**Comment by blaxxun-boop** [comment]
I really don't think that's worth the effort. It's not like Valheim has a sophisticated character creation, where you spend hours on your character. And this would actually be a lot of work, because ServerCharacters keeps your character local, so you do not appear naked in the character selection menu, can keep your character, if the server is wiped and can use it to play in singleplayer worlds as well. So, there would be a lot of checking involved, to make sure that people do not accidentally wipe their character saves, when connecting to a server with the wrong character.
