### ISSUE TITLE
1.3.3 does not work on 0.211 anylonger

### ISSUE THREAD

**Issue by Nevcairiel** [blaxxun-boop/ServerCharacters#29]
Unfortunately, after the update to 1.3.3, ServerCharacters as stopped working on 0.211. On a hunch we also tested 0.212 (PTB), and it works there.

Was the update designed for the PTB, or did something slip in accidentally?
Unfortunately Thunderstore has been handing out 1.3.3 with no regards for the version, if this update is only meant to run on the PTB/0.212

This is the error we keep getting, spammed in the log:

```
[Error  : Unity Log] MissingMethodException: void Skills.CheatRaiseSkill(string,single,bool)
Stack trace:
(wrapper dynamic-method) Game.DMD<Game::SpawnPlayer>(Game,UnityEngine.Vector3)
Game.UpdateRespawn (System.Single dt) (at <cdb5bbec33f94182b860ca208c683122>:0)
Game.FixedUpdate () (at <cdb5bbec33f94182b860ca208c683122>:0)
[Info   : Unity Log] 12/01/2022 11:42:52: Destroying old local player
```

**Comment by blaxxun-boop** [comment]
That release is for the PTB, yes. Thunderstore added a new tab on its page and I put the update there.
Unfortunately, there is no way to tell if an update is for the PTB in the mod managers, so I guess it's back to waiting for the official Mistlands release, before releasing updates for it.

My recommendation for now: Do not update any mods that the mod managers tell you to update, because they are most likely for the PTB.
