### ISSUE TITLE
Characters reset position, map, and stats, but keep items after a relog

### ISSUE THREAD

**Issue by casualelephant** [blaxxun-boop/ServerCharacters#31]
There is an issue where character position, map, and stats are not being saved.
*edit*
This is happening on the windows version. the server log is logging:

> [Message:Server Characters] Backed up a player profile in 'Steam_76561197970282457_delort-2022-12-10T16-12-42.fch'
> [Message:Server Characters] Client Steam_76561197970282457 succesfully restored an emergency backup for Steam_76561197970282457_delort

**Comment by IvIercenary** [comment]
also having this issue on the windows client, refuses to save skills, character location, map location, and quest progress all reset on relog, Even causes issue for others actively connected to the server, causing lag spike like issues preventing any and all interaction.

**Comment by IvIercenary** [comment]
Found a work around via an closed issue, Seems the new crossplay function has changed how this works and DISABLING crossplay has allowed it to remember the previously mentioned things that it was not saving.

Can confirm that it works on windows server client with disabling crossplay. The issue seems to be between servercharacters and crossplay.

**Comment by luket209** [comment]
> Found a work around via a closed issue, Seems the new crossplay function has changed how this works and DISABLING crossplay has allowed it to remember the previously mentioned things that it was not saving.
> 
> Can confirm that it works on windows server client with disabling crossplay. The issue seems to be between servercharacters and crossplay.

Thank you so much for posting this!
