### ISSUE TITLE
Game version incompatibility on dedicated server

### ISSUE THREAD

**Issue by theamazingfedex** [blaxxun-boop/ServerCharacters#34]
When running a dedicated server, it seems that this mod is appending it's name onto the server's reported version number, so any clients (even clients with the ServerCharacters mod installed locally) get a version mismatch error saying that "Client version `0.212.9` does not match Server version `0.212.9-ServerCharacters`". Is there a config setting or something special I need to change to fix this?

Screenshot for reference: 
![image](https://user-images.githubusercontent.com/6488706/210132054-7b3c2e7e-74d3-43cf-b944-19df4e6527b0.png)

**Comment by theamazingfedex** [comment]
So it turns out that running the server from the same folder with the same config files and plugins causes issues when trying to sync the configs, since it's trying to overwrite the config file while it reads it. Most config files are small enough, but the config for Warfare is huge and ended up causing a race condition. Copying the files to a new folder and launching the server from a separate instance of the files than the game client uses made it all much happier.

_**However**_, ServerCharacters tries (and fails) to find an existing character with the user's name since it hasn't been working til now, but it also doesn't create the server character, I have to manually create it for every player who wants to join.

**Comment by blaxxun-boop** [comment]
You should ignore that stupid Jotunn pop-up, it's wrong in 99% of all cases and just confuses people. Always check the log to see the real reason why connections fail. ServerCharacters modifies the server version and not the client version, so you can play with ServerCharacters installed on your client on a server that doesn't have it installed but not the other way around.

There is no such thing as a race condition with ServerSync. It delays RPC_PeerInfo until all configs are synced, I even tested that with 5 mb files. But yes, having the server and the client in the same directory will cause issues for sure, because there can only be one source of truth for the config.

Lastly, you can enable the backup only mode on the server, which allows pre-existing characters to connect to the server, then have every client connect once, so their characters are saved on the server and then disable it again. Just make sure you have crossplay disabled on the server, because that breaks ServerCharacters currently.
