### ISSUE TITLE
"Failed to connect"

### ISSUE THREAD

**Issue by itsdinkd** [blaxxun-boop/ServerCharacters#39]
After adding ServerCharacters, whenever I try joining my server, I get a FAILED TO CONNECT message.

also, no Character folder was created when server started (I restarted about 3 times now).

**Comment by blaxxun-boop** [comment]
You would have to check your logs or share them here, if you need help. Server and client log, preferably.

**Comment by EhDuh666** [comment]
I've encounter the same problem. It's weird, I'm the only one who's successful to create a new character on the server folder. Everyone else who tried to get on the server has failed to create characters on server, which is weird.

I just solved the problem. The players who wants to join needs to have the ID listed in adminlist first in order to generate a new character profile on the server. This is very odd because it wasn't like that on my other save
