### ISSUE TITLE
Is it possible to require only some clients to use this mod?

### ISSUE THREAD

**Issue by DeveloperBlue** [blaxxun-boop/ServerCharacters#54]
I'm in a unique situation where for 2 of my 7 players, the game constantly crashes due to strange hardware/bios/software compatibility issues. This is causing their characters to lose their data, and the client rollbacks are not helping. Frankly we're pulling our brains out trying to narrow down the issues and have gone through a number of guides.

I was wondering if it was possible to enforce server-character saves for just those 2 players (I would install the server mod, they would install the client mod) and the remaining 5 players that have no issues would still be able to join and play without any work on their end.

Is this possible? Thank you!

**Comment by blaxxun-boop** [comment]
No, that's not possible. If you install ServerCharacters on the server, then everyone client needs to install it as well.

If you do not want to enforce anything, but only keep character backups on the server, there is a backup only mode in ServerCharacters that can be toggled on in the configuration.

However, depending on the kind of crash, it might not prevent any rollbacks of characters, if they keep crashing, since it's still the client that does the save, it only sends the file to the server after the saving is done.
